# This property file describes how to replicate EMOP data from Emlite meters
#
# if specified this is where downloads are placed
rootfolder=/var/syncthing/WLCE/replicas

# if specified sleep this many seconds between download attempts
# downloader.sleepseconds=3
sleepseconds=1

# if yes run only groups with .testmode=yes
# testmode=yes

esco=WLCE

meter-0001.folder=Plot-01.C
#meter-0001.ElA=.C
#meter-0001.ElB=.H
meter-0001.startdate=2025-11-01
meter-0001.test=yes

## First usage was in November (Start month for A & date for B.  Monthlies for A (missing Jan) & B (all)
## Check billing data
## Collect from 10th Dec 2021

meter-0002.folder=Plot-02.C
meter-0002.startdate=2025-11-01
meter-0002.test=yes

# First usage was 26th Oct 2021 (start for A&B, plus monthlies for A&B)
# Check for missing intervals.
# Collect from 1st Jan 2022

meter-0003.folder=Plot-03.C
meter-0003.startdate=2025-11-01
meter-0003.test=yes

## First usage was 25th Feb 2022 (Start date for A & pending for B.  Monthlies pending)
## Check for missing intervals.
## Collect from 16th Dec 2021

meter-0004.folder=Plot-04.C
meter-0004.startdate=2025-11-01
meter-0004.test=yes
# 4.C comms might be slow, bypass if need to run batch.

## First usage was in Nov 2021 (start before Dec for A & pending start for B.  Monthlies from Dec for A & pending for B)
## Check billing data
## Collect from 1st Jan 2022

meter-0005.folder=Plot-05.C
meter-0005.startdate=2025-11-01
meter-0005.test=yes

## First usage was in November(start ? for A & ? B.  Monthlies for A & B (both missing Jan)
## Check billing data
## Collect from 1st Jan 2022

meter-0006.folder=Plot-06.C
meter-0006.startdate=2025-11-01
meter-0006.test=yes

## First usage was in November for A.  (start month for A & pending for B .  Monthlies for A (missing Jan) & pending for B).
## Check billing data
## Collect from 1st Jan 2022

meter-0007.folder=Plot-07.C
meter-0007.startdate=2025-11-01
meter-0007.test=yes

## First usage was in Nov 2021 (Start month for A & pending for B.  Monthlies fro A (missing Jan) & pending for B)
## Check billing data
## Collect from 16th Nov 2021

meter-0008.folder=Plot-08.C
meter-0008.startdate=2025-11-01
meter-0008.test=yes

meter-0009.folder=Plot-09.C
meter-0009.startdate=2025-11-01
meter-0009.test=yes

meter-0010.folder=Plot-10.C
meter-0010.startdate=2025-11-01
meter-0010.test=yes

meter-0011.folder=Plot-11.C
meter-0011.startdate=2025-11-01
meter-0011.test=yes

meter-0012.folder=Plot-12.C
meter-0012.startdate=2025-11-01
meter-0012.test=yes

meter-0013.folder=Plot-13.C
meter-0013.startdate=2025-11-01
meter-0013.test=yes

meter-0014.folder=Plot-14.C
meter-0014.startdate=2025-11-01
meter-0014.test=yes

meter-0015.folder=Plot-15.C
meter-0015.startdate=2025-11-01
meter-0015.test=yes

meter-0016.folder=Plot-16.C
meter-0016.startdate=2025-11-01
meter-0016.test=yes

meter-0017.folder=Plot-17.C
meter-0017.startdate=2025-11-01
meter-0017.test=yes

# Data start from 6-Sep-2022

meter-0020.folder=Plot-20.C
meter-0020.startdate=2025-11-01
meter-0020.test=yes

# Data start from 6-Sep-2022

meter-0021.folder=Plot-21.C
meter-0021.startdate=2025-11-01
meter-0021.test=yes

# Data start from 6-Sep-2022

meter-0022.folder=Plot-22.C
meter-0022.startdate=2025-11-01
meter-0022.test=yes

# Data start from 6-Sep-2022

meter-0023.folder=Plot-23.C
meter-0023.startdate=2025-11-01
meter-0023.test=yes

#################################
#### Appartment Meter Points ####
#################################

# Consumption starts 14-Sep-2022

meter-0101.folder=Plot-18b.C
meter-0101.startdate=2025-11-01
meter-0101.test=yes

# Data start from 22-Jul-2022

meter-0102.folder=Plot-18c.C
meter-0102.startdate=2025-11-01
meter-0102.test=yes

# Consumption starts 09-Sep-2022

meter-0103.folder=Plot-19b.C
meter-0103.startdate=2025-11-01
meter-0103.test=yes             # 10th Nov

# Consumption starts 29-Sep-2022

meter-0104.folder=Plot-19c.C
meter-0104.startdate=2025-11-01
meter-0104.test=yes

# Consumption starts 03-Oct-2022

meter-0105.folder=Plot-24b.C
meter-0105.startdate=2025-11-01
meter-0105.test=yes

# Consumption starts 31-Aug-2022

meter-0106.folder=Plot-24c.C
meter-0106.startdate=2025-11-01
meter-0106.test=yes

# Consumption starts 22-Sep-2022

meter-0107.folder=Plot-25b.C
meter-0107.startdate=2025-11-01
meter-0107.test=yes

# Consumption starts 17-Oct-2022

meter-0108.folder=Plot-25c.C
meter-0108.startdate=2025-11-01
meter-0108.test=yes

# Data start from 12-Sep-2022

meter-0109.folder=Plot-24a.C
meter-0109.startdate=2025-11-01
meter-0109.test=yes

# Data start from 01-Sep-2022

meter-0110.folder=Plot-18a.C
meter-0110.startdate=2025-11-01
meter-0110.test=yes

# Data start from 01-Sep-2022

meter-0111.folder=Plot-19a.C
meter-0111.startdate=2025-11-01
meter-0111.test=yes

# Not online yet.

meter-0112.folder=Plot-25a.C
meter-0112.startdate=2025-11-01
meter-0112.test=yes

meter-1819.folder=Plot-18-19.C
meter-1819.startdate=2025-11-01
meter-1819.test=yes

meter-2425.folder=Plot-24-25.C
meter-2425.startdate=2025-11-01
meter-2425.test=yes

meter-ucroft.folder=Undercroft.C
meter-ucroft.startdate=2025-11-01
meter-ucroft.test=yes




# ############################
# #### Solar Meter Points ####
# ############################

# ## First usage was 23rd Dec 2021 (start date for A & no B (solar).  Monthlies for A)
# ## Check billing data
# ## Collect from 1st Feb 2022
# #
# ## OFF-LINE 28/3/2022 - [system offline for some reason]
# #
# meter-0208.folder=Plot-08.G
# meter-0208.startdate=2025-11-01
# meter-0208.test=yes

# meter-0211.folder=Plot-18-19.G
# meter-0211.startdate=2025-11-01
# meter-0211.test=yes

# meter-0212.folder=Plot-24-25.G
# meter-0212.startdate=2025-11-01
# meter-0212.test=yes
